name: mydonet project

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout source code
      - name: Checkout code
        uses: actions/checkout@v5

      # Step 2: Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.100"

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore src/Presentation/Nop.Web/Nop.Web.csproj

      # Step 4: Build project
      - name: Build project
        run: dotnet build src/Presentation/Nop.Web/Nop.Web.csproj --configuration Release --no-restore

      # Step 5: SonarCloud Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Nandini1229_nopCommerce
            -Dsonar.organization=Nandini1229
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.verbose=true

      # Step 6: Publish build output
      - name: Publish .NET app
        run: dotnet publish src/Presentation/Nop.Web/Nop.Web.csproj -c Release -o pillakattupula_Nandhini
